kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python:3.7
  commands:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -e.[all]
    - ./run-tests.sh

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success

- name: docker-registry
  image: plugins/docker
  network_mode: bridge
  settings:
    repo: registry.dpi.inpe.br/${DRONE_REPO}
    registry: registry.dpi.inpe.br
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pass
    auto_tag: true
